<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>
<?php $dataHelper = $this->helper('MageArray\StorePickup\Helper\Data');?>
<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php /* @escapeNotVerified */ echo __('Track Order') ?>"><?php /* @escapeNotVerified */ echo __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?php echo $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?php /* @escapeNotVerified */ echo $_excl; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
            <?php endif; ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
        <?php endif; ?>
		<?php if ($order->getShippingMethod(true)->getCarrierCode() == "storepickup") :?>
			<?php if($dataHelper->disablePickupDate() != 1):?>
				<?php $dateInfo = "";?>
				<?php if( strtotime($order->getPickupDate()) < 0 || strtotime($order->getPickupDate()) === false):?>
					<?php $dateInfo = "Pickup Date is not selected";?>
				<?php else: ?>	
					<?php $dateInfo = date("Y-m-d", strtotime($order->getPickupDate()));?>
				<?php endif; ?>	
				<div>
					<strong><?php echo __("Pickup Date:")?></strong>
					<span>
						<?php echo $dateInfo;?>
					</span>
				</div>	
			<?php endif; ?>	
			<div>
				<strong><?php echo __("Working Hours:")?></strong>
				<span>
					<?php echo $dataHelper->getWorkingHour($order->getPickupStore());?>
				</span>
			</div>	
		<?php endif; ?>
    </div>
</div>
