<?php

$objm = \Magento\Framework\App\ObjectManager::getInstance();
 $customerSession = $objm->get('Magento\Customer\Model\Session');
 if($customerSession->isLoggedIn()) 
 {
 $sc=  $customerSession->getCustomer()->getShippingCode();
 // use your custom attribute name to get the value.
 } else{
 $sc='';
 }

?>
    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br>

        <div class="field shipping_code required">
            <label for="shipping_code" class="label"><span><?php /* @escapeNotVerified */ echo __('Shipping Post Code') ?></span></label>
            <div class="control">
                <a name="code"></a>
                <input type="text" name="shipping_code" id="shipping_code" title="<?php /* @escapeNotVerified */ echo __('Shipping Post Code') ?>" class="input-text" data-validate="{required:true}" autocomplete="off" value="<?php echo $sc;?>">
            </div>
        </div>
    </fieldset>
