<div class="block" data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-background-type="image" data-video-loop="true" data-video-play-only-visible="true" data-video-lazy-load="true" data-video-fallback-src="" data-element="inner" data-pb-style="ILSH52C">
   <h2 class="block-title" data-content-type="heading" data-appearance="default" data-element="main" data-pb-style="AOQM8WT">Shop By Category</h2>
</div>
<!-- <div class="category-image-slider ">
<div class="pagebuilder-slider" data-appearance="default" data-autoplay="false" data-autoplay-speed="4000" data-content-type="slider" data-element="main" data-fade="false" data-infinite-loop="false" data-pb-style="GJ0UQOV" data-show-arrows="true" data-show-dots="false" data-slides-to-show="4"> -->
<div class="images_categories">
   <div class="item">
      <a class="menu-link" href="fresh-vegetables.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresFresh_Fruits.jpg' ?>">
            </picture>
         </i>
         <span>Fruit &amp; Vegetables</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="home-decor.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresHome_Decor.jpg' ?>">
            </picture>
         </i>
         <span>Home Decor</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="Spices.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresSpices.jpg' ?>">
            </picture>
         </i>
         <span>Spices</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="latest-products.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresLatest_Products.jpg' ?>">
            </picture>
         </i>
         <span>Latest Products</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="chings-products.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresNoodles.jpg' ?>">
            </picture>
         </i>
         <span>Noodles</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="rice.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresRice.jpg' ?>">
            </picture>
         </i>
         <span>Rice</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="drinks.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresBeverage.jpg' ?>">
            </picture>
         </i>
         <span>Beverages</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="daily-groceries.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresDayli_Groceries.jpg' ?>">
            </picture>
         </i>
         <span>Daily Groceries</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="maharashtra-specials.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresMaharahstra.jpg' ?>">
            </picture>
         </i>
         <span>maharashtra specials</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="kitchenware-and-appliances.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresKitchen_Stuff.jpg' ?>">
            </picture>
         </i>
         <span>Kitchenware </span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="biscuits-and-cookies.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresChocolate.jpg' ?>">
            </picture>
         </i>
         <span>Biscuits/ Cookies</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="ready-to-eat.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresBF_Ready_to_eat.jpg' ?>">
            </picture>
         </i>
         <span>Breakfast Mixes</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="chat.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresNoodles.jpg' ?>">
            </picture>
         </i>
         <span>Chat/Snacks</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="clearance.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresSALE.jpg' ?>">
            </picture>
         </i>
         <span>Sale</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="dairy-products.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresDayri_Products.jpg' ?>">
            </picture>
         </i>
         <span>Dairy Products</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="dhal-lentils.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresDhal_Lentils.jpg' ?>">
            </picture>
         </i>
         <span>Dhal / Lentils</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="Flour.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresFlour.jpg' ?>">
            </picture>
         </i>
         <span>Flour</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="frozen-items.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresFrozen_Itens.jpg' ?>">
            </picture>
         </i>
         <span>Frozen Items</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="ginger-garlic.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresGinger_and_Garlic.jpg' ?>">
            </picture>
         </i>
         <span>Ginger/ Garlic</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="shan-mixes.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresSugar_and_Salt.jpg' ?>">
            </picture>
         </i>
         <span>masala</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="millets.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresMilets_Quinoa.jpg' ?>">
            </picture>
         </i>
         <span>Millets/ Quinoa</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="mukhwas-candies.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresCandy.jpg' ?>">
            </picture>
         </i>
         <span>Mukhwas&amp; Candies</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="oil-ghee.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresOil.jpg' ?>">
            </picture>
         </i>
         <span>Oil/Ghee</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="organic-products.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresOrganic.jpg' ?>">
            </picture>
         </i>
         <span>Organic Products</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="Pappadams.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresPappadams_copy.jpg' ?>">
            </picture>
         </i>
         <span>Pappadams</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="personal-needs.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresHome_Decor.jpg' ?>">
            </picture>
         </i>
         <span>Personal Needs</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="chutneys-sauces.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresPickles_Souces.jpg' ?>">
            </picture>
         </i>
         <span>Pickles/ Sauces</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="pooja-items.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresPooja_itens.jpg' ?>">
            </picture>
         </i>
         <span>Pooja Items</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="Sweets.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresSweets.jpg' ?>">
            </picture>
         </i>
         <span>Sweets</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="special-products.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresSpecial_Producs.jpg' ?>">
            </picture>
         </i>
         <span>Special Products</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="gujarathi-specials.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresGujarathi.jpg' ?>">
            </picture>
         </i>
         <span>Gujarathi specials</span>
      </a>
   </div>
   <div class="item">
      <a class="menu-link" href="telugu-foods-specials.html">
         <i class="menu-icon img-icon">
            <picture>
               <img src="<?= $this->getUrl('pub/media') . 'colouresTelogu.jpg' ?>">
            </picture>
         </i>
         <span>Telugu foods</span>
      </a>
   </div>
</div>
<!-- </div>
</div> -->