<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$boldText = "";
$center = "style='text-align: center'";

if($_item->getQtyOrdered() > 1){
    $boldText = "style='color: #59b210;font-weight: bold;'";
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getProductId());
$specialprice = $product->getSpecialPrice();
$specialPriceFromDate = $product->getSpecialFromDate();
$specialPriceToDate = $product->getSpecialToDate();

$today =  time();
/*$taxAmountPercent = $product->getTaxClassId();
$tax_amountPrice = "";

if($taxAmountPercent==10){
$tax_amount =(($product->getFinalPrice()*$taxAmountPercent) / 100 ) * $_item->getQtyOrdered();
$tax_amountPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($tax_amount,true,false);
}
*/
$tax_amountPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getTaxAmount(),true,false);

?>
<tr style="border-bottom: 1px dotted;">
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"  <?php echo $boldText;?>><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php
        /** @var \Magento\Sales\Model\Order\Item $_item */
        $options = $_item->getData('product_options');
        ?>
        <?php if ($block->getItemOptions() || $options): ?>
            <dl class="item-options">
                <?php if (isset($options['info_buyRequest']['weight']) && isset($options['info_buyRequest']['item_qty'])) :?>
                    <?php $detailWeight = str_replace(['|', ':'], ['; ', 'gm x '], $options['info_buyRequest']['item_qty'])?>
                    <dt><?= /* @escapeNotVerified */ __('Weight')?>:</dt>
                    <dd><?= /* @escapeNotVerified */ __('%1gm (%2)', $options['info_buyRequest']['weight'], $detailWeight)?></dd>
                    <?php endif;?>
                <?php if($block->getItemOptions()):?>
                    <?php foreach ($block->getItemOptions() as $option): ?>
                        <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                        <dd>
                            <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                        </dd>
                        <?php endforeach; ?>
                    <?php endif;?>
            </dl>
            <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription());

        $discountPriceCal1 = 0;
        if($_item->getDiscountAmount()){
            $discountPriceCal1 = $_item->getDiscountAmount();

        }

        $totalDiscountprice = 0;

        if($specialprice && ($_item->getOriginalPrice()>$_item->getBasePriceInclTax())){
            $mainprice = $_item->getBasePriceInclTax();
            $discountPrice = $_item->getOriginalPrice()-$mainprice;
            $discountPriceCal=  $discountPrice*$_item->getQtyOrdered();
            $totalDiscountprice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($discountPriceCal,true,false);

            ?>

            <p class="sku"><?= /* @escapeNotVerified */  __('Original price') ?>: <?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getPrice(),true,false); ?></p>
            <p class="sku" style='color: #59b210;font-weight: bold;'><?= /* @escapeNotVerified */  __('Saving') ?>: <?=  $totalDiscountprice; ?></p>
            <?php } ?>
    </td>
    <td class="item-info" ><?=  $product->getAttributeText('aisle'); ?></td>
    <td class="item-qty"  <?php echo $boldText;?>><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <?php
    if($specialprice || ($_item->getOriginalPrice()>$product->getFinalPrice())){
        /*   $mainprice = $product->getPrice();
        $discountPrice = $mainprice-$product->getSpecialPrice();*/ ?>
        <td class="item-actualprice" <?php echo $boldText;?>>
            <?=   $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getBasePriceInclTax(),true,false); ?>
        </td>


        <?php } else{
        ?>
        <td class="item-actualprice" <?php echo $boldText;?> >
            <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getBasePriceInclTax(),true,false); ?>
        </td>

        <?php }
    $discountPriceCalwithotherdiscount = $_item->getDiscountAmount();
    ?>


    <?php  if($_item->getQtyOrdered() > 1){

        ?>
        <td class="item-discount" style="color: #59b210;font-weight: bold;text-align: center;">
            <?= /* @escapeNotVerified */  '-'.$this->helper('Magento\Framework\Pricing\Helper\Data')->currency($discountPriceCalwithotherdiscount,true,false); ?>
        </td>
        <td class="item-gst"style='color: #59b210;font-weight: bold;text-align: center;' >
        <?= /* @escapeNotVerified */ $tax_amountPrice?$tax_amountPrice:'N/A' ?>
        </td>
        <?php
        if($product->getRequiredWeight()) {
            $netprice = $_item->getBasePriceInclTax()*$_item->getQtyOrdered();

        }else{
            $netprice = $_item->getBasePriceInclTax()*$_item->getQtyOrdered();

        }
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $currency = $objectManager->get('Magento\Directory\Model\Currency');
        $totalDiscountprice1 = $currency->format($discountPriceCal1, ['display'=>\Magento\Framework\Currency::NO_SYMBOL], false);
        $net =$netprice-$totalDiscountprice1;

        ?>
        <td class="item-price" style='color: #59b210;font-weight: bold;text-align: center;' >
            <?= /* @escapeNotVerified */  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($net,true,false); ?>
        </td>

        <?php } else {
        if($_item->getDiscountAmount()>0){
            ?>
            <td class="item-discount" style="color: #59b210;font-weight: bold;text-align: center;">
                <?= /* @escapeNotVerified */  '-'.$this->helper('Magento\Framework\Pricing\Helper\Data')->currency($discountPriceCalwithotherdiscount,true,false); ?>
            </td>
            <?php }else{ ?>
            <td class="item-discount" style="text-align: center;">
                <?= /* @escapeNotVerified */  '-'.$this->helper('Magento\Framework\Pricing\Helper\Data')->currency($discountPriceCalwithotherdiscount,true,false); ?>
            </td>
            <?php  } ?>
        <td class="item-gst"style='text-align: center;' >
        <?= /* @escapeNotVerified */ $tax_amountPrice?$tax_amountPrice:'N/A' ?>
        </td>
        <?php
        if($product->getRequiredWeight()) {
            $netprice = $_item->getBasePriceInclTax()*$_item->getQtyOrdered();

        }else{
            $netprice = $_item->getBasePriceInclTax()*$_item->getQtyOrdered();

        }
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $currency = $objectManager->get('Magento\Directory\Model\Currency');
        $totalDiscountprice1 = $currency->format($discountPriceCal1, ['display'=>\Magento\Framework\Currency::NO_SYMBOL], false);
        $net =$netprice-$totalDiscountprice1;

        ?>
        <td class="item-price" <?php echo $center;?> >
            <?= /* @escapeNotVerified */  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($net,true,false); ?>
        </td>
        <?php    } ?>

</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <?php endif; ?>
