<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
?>
<?php
/**
 * Product list template
 * * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection1 = $block->getLoadedProductCollection();
$inStock = [];
$outOfStock = [];
foreach ($_productCollection1 as $_product) {
    if ($_product->isSaleable()) {
        $inStock[] = $_product;
    } else {
        $outOfStock[] = $_product;
    }
}
$_productCollection = array_merge($inStock, $outOfStock);
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection1->count()) : ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else : ?>
    <?php echo  $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <li class="item product product-item">
                    <div class="product-item-info" id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <?php 
                        ?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php if ($_product->isAvailable()) { ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php }
                            $expireDate_attribute = $_product->getResource()->getAttribute('previous_order_expiry_date');
                            if ($expireDate_attribute->getFrontend()->getValue($_product) && $_product->isSaleable()) {
                                $date = str_replace('/', '-', $expireDate_attribute->getFrontend()->getValue($_product));
                                $to_date = strtotime(date('Y-m-d'));
                                $ex_date = strtotime(date("Y-m-d", strtotime($date)));
                                if ($to_date > $ex_date || $to_date === $ex_date) {
                                    $clr = "red";
                                } else {
                                    $clr = "#000";
                                }
                                $expireDate = date("d-M-Y", strtotime($date));
                            ?>
                                <div class="expire-date" style="color:<?= $clr ?>;">
                                    <span>Best Before Date : <b><?php echo $expireDate; ?></b></span>
                                </div>
                            <?php } else { ?>
                                <div class="expire-date" style="color: #fff;">
                                    <span>Best Before Date :</span>
                                </div>
                            <?php } ?>
                            <span class="t_price" style="color:#e64834;font-size: 14px;">
                                <?php
                                if ($_product->isAvailable()) :
                                    if ($_product->getTierPrice()) {
                                        $tier_price = $_product->getTierPrice();
                                        foreach ($tier_price as $key => $value) {
                                            $qty = (int)$value['price_qty'];
                                            $price = $value['price'];
                                            $formattedPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($price, 2), true, false);
                                            $finalPrice = $_product->getFinalPrice();
                                            $valuePrice = $value['price'];
                                            if ($finalPrice !== 0) {
                                                $savePercentageFormat = ceil(100 - ((100 / $finalPrice) * $valuePrice)) . "%";
                                            } else {
                                                $savePercentageFormat = "N/A";
                                            }
                                        }
                                    }
                                endif; ?>
                            </span>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_product->isSaleable()) : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" data-mage-init='{"catalogAddToCart": {}}' method="post">
                                                <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?><?php foreach ($options as $optionItem) : ?>
                                                    <input type="hidden" name="<?= $escaper->escapeHtml($optionItem['name']) ?>" value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                <?php endforeach; ?>
                                                <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary" disabled>
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <?php if ($_product->isAvailable()) : ?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                </div>
                                            <?php else : ?>
                                                <div class="stock unavailable">
                                                    <span class="action  primary"><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>
                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
                                </div>
                                <?php if (!$_product->isAvailable()) : ?>
                                    <div class="stock unavailable">
                                        <?php
                                        $formKey = $this->helper('Superbazaar\General\Helper\Data')->getFormKey();
                                        $this->urlHelper = $this->helper('Magento\Framework\Url\Helper\Data');
                                        ?>
                                        <a href="<?php echo $this->getUrl(
                                                        'productalert/add/stock',
                                                        [
                                                            'product_id' => $_product->getId(),
                                                            \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED => $this->urlHelper->getEncodedUrl()
                                                        ]
                                                    ); ?>" title="Notify me when this product is in stock" class="action alert">
                                            <?php echo __("Notify me when this product is in stock"); ?> </a>
                                    </div>
                                <?php endif; ?>
                                <?php if ($showDescription) : ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" title="<?= /* @noEscape */ $_productNameStripped ?>" class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                        ) : '' ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php
    ?>
    <?php 
    ?>
<?php endif; ?>